# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Object'
        db.create_table(u'foreign_estate_object', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('url', self.gf('django.db.models.fields.CharField')(max_length=400, null=True, blank=True)),
            ('date', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('currency', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('price_sell', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('price_rent_monthly', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('price_rent_weekly', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('address', self.gf('django.db.models.fields.CharField')(max_length=500, null=True, blank=True)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('region', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('locality', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('lat', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('lng', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('purpose', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('object_type', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('area_object', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('area_land', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('area_living', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('construction_year', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('rooms_living', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('rooms_combined', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('floors', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('floor', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('bathrooms', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('rooms_sauna', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('pool', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('garden', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('parking', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('price_sell_e', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('price_sell_u', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('price_sell_r', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('balcony', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('window_view', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('terrace', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('internet', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('wc', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('tv', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('fitness', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('furnished', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('first_line', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('garage', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('garage_cars', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('personal_beach', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('private_gym', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('supermarket', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('private_tennis_court', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('rooms_terrace', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('rooms_balcony', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('private_territory', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('private_beach', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('private_pier', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('golf', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('golf_field', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('distance_parking', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('distance_supermarket', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('distance_sea', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('distance_mountains', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('description_short', self.gf('django.db.models.fields.CharField')(max_length=500, null=True, blank=True)),
            ('description_full', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('photos', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('video_link', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('video_link2', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
        ))
        db.send_create_signal(u'foreign_estate', ['Object'])


    def backwards(self, orm):
        # Deleting model 'Object'
        db.delete_table(u'foreign_estate_object')


    models = {
        u'foreign_estate.object': {
            'Meta': {'object_name': 'Object'},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '500', 'null': 'True', 'blank': 'True'}),
            'area_land': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'area_living': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'area_object': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'balcony': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'bathrooms': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'construction_year': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'currency': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'date': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'description_full': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_short': ('django.db.models.fields.CharField', [], {'max_length': '500', 'null': 'True', 'blank': 'True'}),
            'distance_mountains': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'distance_parking': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'distance_sea': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'distance_supermarket': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'first_line': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fitness': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'floor': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'floors': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'furnished': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'garage': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'garage_cars': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'garden': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'golf': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'golf_field': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'internet': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lat': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'lng': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'locality': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'object_type': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'parking': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'personal_beach': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'photos': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'pool': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'price_rent_monthly': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_rent_weekly': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_sell': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_sell_e': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_sell_r': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_sell_u': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'private_beach': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'private_gym': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'private_pier': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'private_tennis_court': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'private_territory': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'purpose': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'rooms_balcony': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rooms_combined': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rooms_living': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rooms_sauna': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rooms_terrace': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'supermarket': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'terrace': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'tv': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'url': ('django.db.models.fields.CharField', [], {'max_length': '400', 'null': 'True', 'blank': 'True'}),
            'video_link': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'video_link2': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'wc': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'window_view': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['foreign_estate']